//! RandomX consensus vectors.
//!
//! Two layers of vectors:
//!   1. `seed_height` schedule (RFC-0011): cheap, no RandomX execution.
//!   2. Frozen hash vector: a known (seed, preimage) → hash binding. Any
//!      change in upstream `randomx-rs`, RandomX library version, or input
//!      encoding will trip this test.
//!
//! The frozen vector was generated by `examples/print_randomx_vector.rs` on
//! the reference build. To reproduce independently, run RandomX (any
//! implementation) over the documented `seed` and `preimage` and compare.

use dom_pow::{randomx_pool::randomx_hash, randomx_seed_height, validate_pow_randomx};

#[test]
fn vector_genesis_block() {
    let seed_height = randomx_seed_height(0);
    assert_eq!(seed_height, 0);
}

#[test]
fn vector_height_2048_first_rotation() {
    let seed_height = randomx_seed_height(2048);
    assert_eq!(seed_height, 1984);
}

#[test]
fn vector_height_4096_second_rotation() {
    let seed_height = randomx_seed_height(4096);
    assert_eq!(seed_height, 4032);
}

/// Frozen RandomX hash vector — consensus-critical.
///
/// Inputs:
///   seed     = [0; 32]
///   preimage = b"DOM/randomx/v1/vector/genesis"
///
/// Expected output is the canonical RandomX hash bytes.
/// Any deviation indicates a RandomX implementation or upstream API drift —
/// this is a HARD FORK and must not pass silently.
#[test]
fn vector_frozen_hash_genesis_preimage() {
    let seed = [0u8; 32];
    let preimage = b"DOM/randomx/v1/vector/genesis";
    let expected: [u8; 32] =
        hex32("5fb8aaf461cbbaf36d5e702afd2ecdda110777bf5b8481739f4dd07764401c9f");

    let got = randomx_hash(&seed, preimage).expect("randomx hash");
    assert_eq!(
        got, expected,
        "RandomX hash drift detected — investigate randomx-rs version or RandomX library before changing this vector"
    );

    // And the high-level validator must accept it against a permissive target.
    let permissive_target = [0xff_u8; 32];
    let ok = validate_pow_randomx(preimage, &expected, &seed, &permissive_target)
        .expect("validate_pow_randomx");
    assert!(ok, "validator must accept the frozen vector");
}

fn hex32(s: &str) -> [u8; 32] {
    assert_eq!(s.len(), 64, "hex must be 64 chars");
    let mut out = [0u8; 32];
    for (i, chunk) in s.as_bytes().chunks(2).enumerate() {
        let hi = hex_nibble(chunk[0]);
        let lo = hex_nibble(chunk[1]);
        out[i] = (hi << 4) | lo;
    }
    out
}

fn hex_nibble(c: u8) -> u8 {
    match c {
        b'0'..=b'9' => c - b'0',
        b'a'..=b'f' => c - b'a' + 10,
        b'A'..=b'F' => c - b'A' + 10,
        _ => panic!("not hex: {c}"),
    }
}
