[package]
name = "solana-program-attestation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
thiserror = { workspace = true }
sha2 = { workspace = true }
solana-types = { path = "../solana-types" }
solana-rpc = { path = "../solana-rpc" }
solana-rpc-pool = { path = "../solana-rpc-pool" }
