//! Library surface of the generator, exposed for its own integration tests.
#![forbid(unsafe_code)]

use std::path::PathBuf;

/// Builds the canonical V1 chain-services document from mold facts, through
/// the daemon's own validated writer — the generated bytes are the daemon's
/// canonical encoding by construction, never a hand-formatted imitation.
pub fn chain_services_document(mold: &serde_json::Value) -> Result<Vec<u8>, String> {
    let evm_rpc = require_str(mold, &["evm", "rpc"])?;
    let datadir = require_str(mold, &["bitcoin", "datadir"])?;
    let rpc_port = require_u64(mold, &["bitcoin", "rpc_port"])?;
    let wallet = require_str(mold, &["bitcoin", "wallet"])?;
    let config = dom_interopd::ProductionChainServicesConfigV1::from_parts(
        evm_rpc,
        format!("http://127.0.0.1:{rpc_port}"),
        wallet,
        PathBuf::from(format!("{datadir}/regtest/.cookie")),
        20,
    )
    .map_err(|error| format!("chain services refused: {error}"))?;
    config
        .canonical_bytes()
        .map_err(|error| format!("chain services encode: {error}"))
}

fn require_str(mold: &serde_json::Value, path: &[&str]) -> Result<String, String> {
    let mut value = mold;
    for key in path {
        value = value
            .get(key)
            .ok_or_else(|| format!("mold missing {}", path.join(".")))?;
    }
    value
        .as_str()
        .map(str::to_owned)
        .ok_or_else(|| format!("mold field {} is not a string", path.join(".")))
}

fn require_u64(mold: &serde_json::Value, path: &[&str]) -> Result<u64, String> {
    let mut value = mold;
    for key in path {
        value = value
            .get(key)
            .ok_or_else(|| format!("mold missing {}", path.join(".")))?;
    }
    value
        .as_u64()
        .ok_or_else(|| format!("mold field {} is not a u64", path.join(".")))
}
