//! Library surface of the generator, exposed for its own integration tests.
#![forbid(unsafe_code)]

use std::path::PathBuf;

/// Builds the canonical V1 chain-services document from mold facts, through
/// the daemon's own validated writer — the generated bytes are the daemon's
/// canonical encoding by construction, never a hand-formatted imitation.
pub fn chain_services_document(mold: &serde_json::Value) -> Result<Vec<u8>, String> {
    let evm_rpc = require_str(mold, &["evm", "rpc"])?;
    let datadir = require_str(mold, &["bitcoin", "datadir"])?;
    let rpc_port = require_u64(mold, &["bitcoin", "rpc_port"])?;
    let wallet = require_str(mold, &["bitcoin", "wallet"])?;
    let config = dom_interopd::ProductionChainServicesConfigV1::from_parts(
        evm_rpc,
        format!("http://127.0.0.1:{rpc_port}"),
        wallet,
        PathBuf::from(format!("{datadir}/regtest/.cookie")),
        20,
    )
    .map_err(|error| format!("chain services refused: {error}"))?;
    config
        .canonical_bytes()
        .map_err(|error| format!("chain services encode: {error}"))
}

fn require_str(mold: &serde_json::Value, path: &[&str]) -> Result<String, String> {
    let mut value = mold;
    for key in path {
        value = value
            .get(key)
            .ok_or_else(|| format!("mold missing {}", path.join(".")))?;
    }
    value
        .as_str()
        .map(str::to_owned)
        .ok_or_else(|| format!("mold field {} is not a string", path.join(".")))
}

fn require_u64(mold: &serde_json::Value, path: &[&str]) -> Result<u64, String> {
    let mut value = mold;
    for key in path {
        value = value
            .get(key)
            .ok_or_else(|| format!("mold missing {}", path.join(".")))?;
    }
    value
        .as_u64()
        .ok_or_else(|| format!("mold field {} is not a u64", path.join(".")))
}

use std::fs;
use std::os::unix::fs::{OpenOptionsExt as _, PermissionsExt as _};
use std::path::Path;

use adapter_btc::timelock::ChainTimingBoundsV1;
use adapter_btc::types::BitcoinNetworkV1;
use btc_crypto::SecpContext;
use chain_profile::{ChainKindV1, ChainProfileV1};
use deployment_registry::{
    AssetBindingV1, AssetRepresentationV1, AuthoritySetV1, BitcoinDeploymentV1, ChainDeploymentV1,
    DomDeploymentV1, DomNetworkV1, DomRuntimeIdentityV1, EvmDeploymentV1, RegistryChainProfileV1,
    RegistryManifestV1, RegistrySignatureV1, RegistryStoreV1, SignedRegistryV1,
};
use dom_consensus::derive_chain_id;
use dom_core::{configured_genesis_hash_for_network_magic, NETWORK_MAGIC_REGTEST};
use kaystra_core::types::{AssetId, ChainId, FinalityPolicyV1};
use rand::RngCore as _;
use zeroize::Zeroizing;

pub use deployment_registry::RegistryValidationPolicyV1;

/// Fixed artifact names of the generated state directory.
pub const REGISTRY_FILE_V1: &str = "registry.v1.sqlite3";
/// Chain-services document name, matching the daemon's fixed name.
pub const CHAIN_SERVICES_FILE_V1: &str = "production-chain-services.v1";
const AUTHORITY_SECRET_PREFIX_V1: &str = "registry-authority";
const NETWORK_ID_DOMAIN_V1: &[u8] = b"DOM-INTEROP/LOCAL-NETWORK-ID/V1\0";
const EPOCH_V1: u64 = 1;
const VALIDITY_SECONDS_V1: u64 = 31_536_000;

/// Everything a provisioning run pins, for the report and the cycle gate.
pub struct ProvisionedRegistryV1 {
    /// Interop network identity the manifest carries.
    pub network_id: [u8; 32],
    /// Installed epoch.
    pub epoch: u64,
    /// Canonical manifest digest.
    pub manifest_digest: [u8; 32],
    /// Verifying authority set (threshold 2 of 3).
    pub authorities: AuthoritySetV1,
    /// Verification context.
    pub secp: SecpContext,
    /// The exact policy the install verified under.
    pub policy: RegistryValidationPolicyV1,
    /// Authority x-only keys, index-ordered.
    pub authority_keys: Vec<[u8; 32]>,
    /// DOM chain id in the manifest.
    pub dom_chain_id: [u8; 32],
}

/// Builds, signs, installs and re-verifies the local-cycle registry.
pub fn provision_registry(
    mold: &serde_json::Value,
    state_dir: &Path,
) -> Result<ProvisionedRegistryV1, String> {
    fs::create_dir_all(state_dir).map_err(|error| format!("state dir: {error}"))?;
    fs::set_permissions(state_dir, fs::Permissions::from_mode(0o700))
        .map_err(|error| format!("state dir mode: {error}"))?;
    let manifest = manifest_from_mold(mold)?;
    let digest = manifest
        .manifest_digest()
        .map_err(|error| format!("manifest digest: {error:?}"))?;
    let secp = SecpContext::new(&random32());
    let mut keys = Vec::new();
    let mut signatures = Vec::new();
    for index in 0_u16..3 {
        let secret = Zeroizing::new(random32());
        let (signature, xonly) = secp
            .sign_bip340(&secret, &digest, &random32())
            .map_err(|error| format!("authority signature: {error:?}"))?;
        write_owner_file(
            &state_dir.join(format!("{AUTHORITY_SECRET_PREFIX_V1}-{index}.secret")),
            hex::encode(&secret[..]).as_bytes(),
        )?;
        keys.push(xonly);
        signatures.push(RegistrySignatureV1 {
            signer_index: index,
            signature,
        });
    }
    let authorities = AuthoritySetV1::new(2, keys.clone())
        .map_err(|error| format!("authority set: {error:?}"))?;
    let signed = SignedRegistryV1::new(&manifest, signatures)
        .map_err(|error| format!("signed registry: {error:?}"))?;
    let registry_path = state_dir.join(REGISTRY_FILE_V1);
    if registry_path.exists() {
        return Err("registry.v1.sqlite3 already exists; refusing to overwrite".into());
    }
    let mut store = RegistryStoreV1::create(&registry_path)
        .map_err(|error| format!("registry create: {error:?}"))?;
    let policy = RegistryValidationPolicyV1 {
        now_seconds: manifest.valid_from,
        expected_network_id: manifest.network_id,
        minimum_epoch: EPOCH_V1,
    };
    store
        .install(&signed, &authorities, &secp, policy)
        .map_err(|error| format!("registry install: {error:?}"))?;
    let reloaded = verify_registry(&registry_path, &authorities, &secp, policy)?;
    if reloaded != digest {
        return Err("reloaded registry digest diverges from the installed manifest".into());
    }
    Ok(ProvisionedRegistryV1 {
        network_id: manifest.network_id,
        epoch: EPOCH_V1,
        manifest_digest: digest,
        authorities,
        secp,
        policy,
        authority_keys: keys,
        dom_chain_id: manifest.dom.chain_id.0,
    })
}

/// Reopens the store and returns the verified current manifest digest.
pub fn verify_registry(
    registry_path: &Path,
    authorities: &AuthoritySetV1,
    secp: &SecpContext,
    policy: RegistryValidationPolicyV1,
) -> Result<[u8; 32], String> {
    let reopened = RegistryStoreV1::open_existing(registry_path)
        .map_err(|error| format!("registry reopen: {error:?}"))?;
    let resolved = reopened
        .load_current(authorities, secp, policy)
        .map_err(|error| format!("registry reload: {error:?}"))?
        .ok_or("registry reload returned no current manifest")?;
    Ok(resolved.manifest_digest())
}

fn manifest_from_mold(mold: &serde_json::Value) -> Result<RegistryManifestV1, String> {
    let genesis = configured_genesis_hash_for_network_magic(NETWORK_MAGIC_REGTEST)
        .map_err(|_| "canonical DOM regtest genesis missing".to_owned())?;
    let dom_chain = ChainId(*derive_chain_id(NETWORK_MAGIC_REGTEST, &genesis).as_bytes());
    let source_commit = require_str(mold, &["source_commit"])?;
    let network_id = domain_digest(NETWORK_ID_DOMAIN_V1, source_commit.as_bytes());
    let evm_chain = ChainId(evm_chain_id_bytes(mold)?);
    let btc_chain = ChainId(bitcoin_chain_id_bytes());
    let dom_asset = AssetId(domain_digest(b"DOM-ASSET/NATIVE/V1\0", &dom_chain.0));
    let evm_native = AssetId(domain_digest(b"DOM-ASSET/EVM-NATIVE/V1\0", &evm_chain.0));
    let btc_asset = AssetId(domain_digest(b"DOM-ASSET/BTC-NATIVE/V1\0", &btc_chain.0));
    let native_lock = require_address(mold, &["evm", "native_lock"])?;
    let native_code_hash = require_hash32(mold, &["evm", "native_runtime_codehash"])?;
    let erc20_lock = require_address(mold, &["evm", "erc20_lock"])?;
    let erc20_code_hash = require_hash32(mold, &["evm", "erc20_runtime_codehash"])?;
    let evm_genesis = require_hash32(mold, &["evm", "genesis_hash"])?;
    let deploy_block = require_u64(mold, &["evm", "deploy_block"])?;
    let btc_genesis = bitcoin_genesis_bytes(mold)?;
    let valid_from = 1;

    let mut manifest = RegistryManifestV1 {
        network_id,
        epoch: EPOCH_V1,
        valid_from,
        expires_at: valid_from + VALIDITY_SECONDS_V1,
        dom: DomDeploymentV1 {
            chain_id: dom_chain,
            genesis_hash: *genesis.as_bytes(),
            runtime_identity: DomRuntimeIdentityV1::pinned(DomNetworkV1::Regtest),
            consensus_rules_digest: domain_digest(
                b"DOM-CONSENSUS-RULES/LOCAL-CYCLE/V1\0",
                source_commit.as_bytes(),
            ),
            scriptless_api_version: 1,
            timing: local_timing(),
            finality: local_finality(),
            native_asset: dom_asset,
        },
        chains: vec![
            RegistryChainProfileV1 {
                profile: ChainProfileV1 {
                    chain_id: evm_chain,
                    kind: ChainKindV1::Evm {
                        evm_chain_id: require_u64(mold, &["evm", "chain_id"])?,
                        native_lock_contract: native_lock,
                        native_code_hash,
                        erc20_lock_contract: Some((erc20_lock, erc20_code_hash)),
                    },
                    timing: local_timing(),
                    finality: local_finality(),
                    native_asset: evm_native,
                    allowed_assets: vec![],
                },
                deployment: ChainDeploymentV1::Evm(EvmDeploymentV1 {
                    genesis_hash: evm_genesis,
                    native_start_block: deploy_block,
                    erc20_start_block: Some(deploy_block),
                    abi_digest: domain_digest(b"DOM-EVM-ABI/LOCAL-CYCLE/V1\0", &native_code_hash),
                    compiler_digest: domain_digest(
                        b"DOM-EVM-COMPILER/LOCAL-CYCLE/V1\0",
                        source_commit.as_bytes(),
                    ),
                    source_digest: domain_digest(
                        b"DOM-EVM-SOURCE/LOCAL-CYCLE/V1\0",
                        source_commit.as_bytes(),
                    ),
                    deployment_digest: domain_digest(
                        b"DOM-EVM-DEPLOYMENT/LOCAL-CYCLE/V1\0",
                        &[native_lock.as_slice(), erc20_lock.as_slice()].concat(),
                    ),
                    finalized_tag_required: true,
                    page_size: 256,
                    gas_limit_hint: 300_000,
                    max_fee_per_gas: 100_000_000_000,
                    max_priority_fee_per_gas: 2_000_000_000,
                }),
            },
            RegistryChainProfileV1 {
                profile: ChainProfileV1 {
                    chain_id: btc_chain,
                    kind: ChainKindV1::Bitcoin {
                        network: BitcoinNetworkV1::Regtest,
                    },
                    timing: local_timing(),
                    finality: local_finality(),
                    native_asset: btc_asset,
                    allowed_assets: vec![],
                },
                deployment: ChainDeploymentV1::Bitcoin(BitcoinDeploymentV1 {
                    genesis_hash: btc_genesis,
                    signet_challenge: vec![],
                    max_fee_rate_sat_vbyte: 100,
                    min_relay_fee_sat_kvb: 1_000,
                }),
            },
        ],
        assets: vec![
            AssetBindingV1 {
                chain_id: dom_chain,
                asset_id: dom_asset,
                decimals: 9,
                representation: AssetRepresentationV1::Native,
            },
            AssetBindingV1 {
                chain_id: evm_chain,
                asset_id: evm_native,
                decimals: 18,
                representation: AssetRepresentationV1::Native,
            },
            AssetBindingV1 {
                chain_id: btc_chain,
                asset_id: btc_asset,
                decimals: 8,
                representation: AssetRepresentationV1::Native,
            },
        ],
    };
    manifest
        .chains
        .sort_by_key(|entry| entry.profile.chain_id.0);
    manifest
        .assets
        .sort_by_key(|asset| (asset.chain_id.0, asset.asset_id.0));
    Ok(manifest)
}

/// Local regtest cadence: one-second dev blocks with shallow finality.
fn local_timing() -> ChainTimingBoundsV1 {
    ChainTimingBoundsV1 {
        min_block_seconds: 1,
        max_block_seconds: 30,
        max_reorg_seconds: 600,
        observation_seconds: 30,
        broadcast_seconds: 20,
    }
}

fn local_finality() -> FinalityPolicyV1 {
    FinalityPolicyV1 {
        min_confirmations: 2,
        max_reorg_depth: 6,
    }
}

fn evm_chain_id_bytes(mold: &serde_json::Value) -> Result<[u8; 32], String> {
    Ok(domain_digest(
        b"DOM-CHAIN-ID/EVM-LOCAL/V1\0",
        &require_u64(mold, &["evm", "chain_id"])?.to_be_bytes(),
    ))
}

fn bitcoin_chain_id_bytes() -> [u8; 32] {
    domain_digest(b"DOM-CHAIN-ID/BTC-REGTEST/V1\0", b"regtest")
}

fn bitcoin_genesis_bytes(mold: &serde_json::Value) -> Result<[u8; 32], String> {
    let display = require_str(mold, &["bitcoin", "genesis_hash"])?;
    let bytes = hex::decode(&display).map_err(|_| "bitcoin genesis is not hex".to_owned())?;
    let array: [u8; 32] = bytes
        .try_into()
        .map_err(|_| "bitcoin genesis is not 32 bytes".to_owned())?;
    // bitcoind displays block hashes byte-reversed; the registry stores raw.
    let mut raw = array;
    raw.reverse();
    Ok(raw)
}

fn domain_digest(domain: &[u8], bytes: &[u8]) -> [u8; 32] {
    use blake2::digest::{Update as _, VariableOutput as _};
    let mut hasher = blake2::Blake2bVar::new(32).expect("blake2 32");
    hasher.update(domain);
    hasher.update(bytes);
    let mut out = [0_u8; 32];
    hasher.finalize_variable(&mut out).expect("blake2 finalize");
    out
}

/// Creates one owner-only (0600) file that must not already exist.
pub fn write_owner_file(path: &Path, bytes: &[u8]) -> Result<(), String> {
    use std::io::Write as _;
    let mut options = fs::OpenOptions::new();
    options.write(true).create_new(true).mode(0o600);
    let mut file = options
        .open(path)
        .map_err(|error| format!("{}: {error}", path.display()))?;
    file.write_all(bytes)
        .map_err(|error| format!("{}: {error}", path.display()))
}

fn require_hash32(mold: &serde_json::Value, path: &[&str]) -> Result<[u8; 32], String> {
    let text = require_str(mold, path)?;
    let text = text.strip_prefix("0x").unwrap_or(&text);
    hex::decode(text)
        .ok()
        .and_then(|bytes| <[u8; 32]>::try_from(bytes).ok())
        .ok_or_else(|| format!("mold field {} is not a 32-byte hex", path.join(".")))
}

fn require_address(mold: &serde_json::Value, path: &[&str]) -> Result<[u8; 20], String> {
    let text = require_str(mold, path)?;
    let text = text.strip_prefix("0x").unwrap_or(&text);
    hex::decode(text)
        .ok()
        .and_then(|bytes| <[u8; 20]>::try_from(bytes).ok())
        .ok_or_else(|| format!("mold field {} is not a 20-byte hex", path.join(".")))
}

fn random32() -> [u8; 32] {
    let mut bytes = [0_u8; 32];
    rand::rngs::OsRng
        .try_fill_bytes(&mut bytes)
        .expect("OS entropy");
    bytes
}
